Catalogue/Models/Review.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Catalogue.Models
{
    /// <summary>
    /// Model for Review entity. Contains a required foreign key to Record entity.
    /// </summary>
    public class Review
    {
        public int Id { get; set; }

        [Required]
        [Range(1, 10, ErrorMessage ="Rating must be between 1 and 10")]
        public int Rating { get; set; }

        [StringLength(80)]
        public string Comment { get; set; }

        public int RecordId { get; set; }
    }
}

Catalogue/Controllers/RecordController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalogue.Models;
using Catalogue.Filters;

namespace Catalogue.Controllers
{
    [CustomErrorHandle]
    [Authorize]
    public class RecordController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Record
        /// <summary>
        /// Displays list of all records from index-catalog. 
        /// Performs filtering if corresponging patameters are specified
        /// </summary>
        /// <param name="searchTerm">Search string</param>
        /// <param name="title">'true' if needed search by record title</param>
        /// <param name="author">'true' if needed search by record author</param>
        /// <param name="desc">'true' if needed search by record description</param>
        /// <param name="owner">'true' if needed search by record owners username</param>
        /// <returns>List of filtered records.</returns>
        [AllowAnonymous]
        public ActionResult Index(string searchTerm = null,
                                    string title = null,
                                    string author = null,
                                    string desc = null,
                                    string owner = null)
        {
            if (searchTerm == null || searchTerm.Equals(""))
            {
                return View(db.Records.ToList());
            }
            else
            {
                searchTerm = searchTerm.Trim();
                var model =
                    db.Records.
                      Where(r => (((title != null) && (-1 != r.Title.IndexOf(searchTerm)))
                                    || ((author != null) && (-1 != r.Author.IndexOf(searchTerm)))
                                    || ((desc != null) && (-1 != r.Description.IndexOf(searchTerm)))
                                    || ((owner != null) && (-1 != r.OwnerName.IndexOf(searchTerm)))
                                    )).
                      Select(r => r);
                return View(model);
            }

        }

        // GET: Record/Create
        /// <summary>
        /// Returns Create Record View.
        /// </summary>
        /// <returns>Returns Create Record View.</returns>
        public ActionResult Create()
        {
            return View();
        }

        // POST: Record/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Saves Record model to database.
        /// </summary>
        /// <returns>Redirect to records list on success
        /// and create record view on failure (with model validation errors)</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Author,Description")] Record record)
        {
            if (ModelState.IsValid)
            {
                record.OwnerName = User.Identity.Name;
                db.Records.Add(record);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(record);
        }

        // GET: Record/Edit/5
        /// <summary>
        /// Returns Edit Record View.
        /// </summary>
        /// <returns>Returns Edit Record View.</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        // POST: Record/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Saves Record model to database.
        /// </summary>
        /// <returns>Redirect to records list on success
        /// and edit record view on failure (with model validation errors)</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Author,Description")] Record record)
        {
            if (ModelState.IsValid)
            {
                record.OwnerName = User.Identity.Name;
                db.Entry(record).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(record);
        }

        // GET: Record/Delete/5
        /// <summary>
        /// Returns Delete Record View.
        /// </summary>
        /// <returns>Returns Delete Record View.</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        // POST: Record/Delete/5
        /// <summary>
        /// Deltes Record model from database.
        /// </summary>
        /// <returns>Redirect to records list</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Record record = db.Records.Find(id);
            db.Records.Remove(record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Catalogue/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalogue.Models;
using Catalogue.Filters;

namespace Catalogue.Controllers
{
    /// <summary>
    /// Controller for performing CRUDL actions for Reviws model.
    /// </summary>
    [CustomErrorHandle]
    [Authorize]
    public class ReviewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Review/Index/2
        /// <summary>
        /// Method to get all information about specified record.
        /// </summary>
        /// <param name="recordId">Id for Record to return.</param>
        /// <returns>Record for specified id.</returns>
        [AllowAnonymous]
        public ActionResult Index([Bind(Prefix = "id")]int? recordId)
        {
            if (recordId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(recordId);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        // GET: Review/Details/5
        /// <summary>
        /// Allows getting detailed information about a given review.
        /// </summary>
        /// <param name="id">Id of review.</param>
        /// <returns>ActionResult with review model.</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // GET: Review/Create
        /// <summary>
        /// Returns Create review View.
        /// </summary>
        /// <param name="recordId">Id of record to add review for.</param>
        /// <returns>Returns Create review View.</returns>
        [AllowAnonymous]
        public ActionResult Create(int recordId)
        {
            return View();
        }

        // POST: Review/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Saves reviw model to database.
        /// </summary>
        /// <param name="review">Model from view to add to database.</param>
        /// <returns>Redirect to record details on success
        /// and create review view on failure (with model validation errors)</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Create(Review review)
        {
            if (ModelState.IsValid)
            {
                db.Reviews.Add(review);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = review.RecordId });
            }

            return View(review);
        }

        // GET: Review/Edit/5
        /// <summary>
        /// Edit review.
        /// </summary>
        /// <param name="id">Specifies review to edit.</param>
        /// <returns>Edit review View.</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Review/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Saves edited review.
        /// </summary>
        /// <param name="review">Review model to save.</param>
        /// <returns>Redirect to record details on success
        /// and create record view on failure (with model validation errors)</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Rating,Comment,RecordId")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Entry(review).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = review.RecordId });
            }
            return View(review);
        }

        // GET: Review/Delete/5
        /// <summary>
        /// Delete review.
        /// </summary>
        /// <param name="id">Specifies review to delete.</param>
        /// <returns>Delete review View.</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = db.Reviews.Find(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Review/Delete/5
        /// <summary>
        /// Deletes chosen review by id.
        /// </summary>
        /// <param name="review">Id of Review to be deleted.</param>
        /// <returns>Redirect to record details.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = db.Reviews.Find(id);
            int? recordId = review.RecordId;
            db.Reviews.Remove(review);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = recordId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Catalogue/Views/Review/Create.cshtml
@model Catalogue.Models.Review

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Catalogue/Views/Review/Delete.cshtml
@model Catalogue.Models.Review

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { Id = Model.RecordId })
        </div>
    }
</div>

Catalogue/Views/Review/Details.cshtml
@model Catalogue.Models.Review

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", new { Id = Model.RecordId })
</p>

Catalogue/Views/Review/Edit.cshtml
@model Catalogue.Models.Review

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.RecordId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { Id = Model.RecordId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Catalogue/Views/Review/Index.cshtml
@model Catalogue.Models.Record

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Record</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>

<div>
    <p>
        @Html.ActionLink("Create new Review", "Create", new { RecordId = Model.Id })
    </p>
    @Html.Partial("_Reviews", @Model.Reviews)
</div>

<p>
    @Html.ActionLink("Edit", "Edit", "Record", new { id = Model.Id }, null) |
    @Html.ActionLink("Back to List", "Index", "Record")
</p>

Catalogue/Views/Review/_Reviews.cshtml
@model IEnumerable<Catalogue.Models.Review>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>